{% set version = "0.9.1" %}

package:
  name: capnproto
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/capnproto/capnproto/archive/v{{ version }}.tar.gz
  md5: 3ba09702784e9ae1d53a5d9de23c6dd7

build:
  number: 0

requirements:
  build:
    - cmake
    - make  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - openssl 1.1*
    - zlib

test:
  commands:
    - capnp --help
    - capnpc --help
    - capnpc-c++ --help
    - capnpc-capnp --help

    - test -d "$PREFIX/include/capnp"  # [unix]
    - if not exist %LIBRARY_INC%\\capnp exit 1  # [win]

    - test -f "$PREFIX/lib/libcapnp.a"  # [unix]
    - test -f "$PREFIX/lib/libcapnpc.a"  # [unix]
    - test -f "$PREFIX/lib/libcapnp-rpc.a"  # [unix]
    - test -f "$PREFIX/lib/libkj.a"  # [unix]
    - test -f "$PREFIX/lib/libkj-async.a"  # [unix]
    - if not exist %LIBRARY_LIB%\\capnp.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\kj.lib exit 1  # [win]

about:
  home: http://capnproto.org
  license_file: LICENSE
  license: MIT
  summary: An insanely fast data interchange format and capability-based RPC system.

extra:
  recipe-maintainers:
    - frol
    - ihnorton
    - Shelnutt2
