{% set version = "1.0.2" %}

package:
  name: capnproto
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/capnproto/capnproto/archive/v{{ version }}.tar.gz
  md5: 4dd1aaacff63781087e89097f9b02542

build:
  number: 1
  run_exports:
    # soname changes with every release
    # https://abi-laboratory.pro/index.php?view=timeline&l=capnproto
    - {{ pin_subpackage('capnproto', max_pin='x.x.x') }}
  ignore_prefix_files:
    - bin/capnp

requirements:
  build:
    - cmake  # [win]
    - make  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - automake   # [unix]
    - libtool    # [unix]
    - binutils    # [unix]
  host:
    - zlib
    - openssl

test:
  source_files:
    - c++/samples
  commands:
    - capnp --help  # [not (osx and arm64)]
    - capnpc --help  # [not (osx and arm64)]
    - capnpc-c++ --help  # [not (osx and arm64)]
    - capnpc-capnp --help  # [not (osx and arm64)]

    - capnpc -I"$PREFIX/include" -oc++ c++/samples/addressbook.capnp  # [unix and (not (osx and arm64))]
    - test -f c++/samples/addressbook.capnp.c++  # [unix and (not (osx and arm64))]

    - capnpc -I"%LIBRARY_INC%" -oc++ c++/samples/addressbook.capnp  # [win]
    - if not exist c++/samples/addressbook.capnp.c++ exit 1  # [win]

    - test -d "$PREFIX/include/capnp"  # [unix]
    - if not exist %LIBRARY_INC%\\capnp exit 1  # [win]

    - test -f "$PREFIX/lib/libcapnp${SHLIB_EXT}"  # [unix]
    - test -f "$PREFIX/lib/libcapnpc${SHLIB_EXT}"  # [unix]
    - test -f "$PREFIX/lib/libcapnp-rpc${SHLIB_EXT}"  # [unix]
    - test -f "$PREFIX/lib/libkj${SHLIB_EXT}"  # [unix]
    - test -f "$PREFIX/lib/libkj-async${SHLIB_EXT}"  # [unix]
    - if not exist %LIBRARY_LIB%\\capnp.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\kj.lib exit 1  # [win]

about:
  home: http://capnproto.org
  license_file: LICENSE
  license: MIT
  summary: An insanely fast data interchange format and capability-based RPC system.

extra:
  recipe-maintainers:
    - LehMaxence
    - ihnorton
    - Shelnutt2
