appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ZxpD0A13U79MnIrCXG+RoY02M2rFH3V2Z46868f0FgX21Otfh7pzliIJl7rxylC7PGY/03Qu9XJ7nidsG3v36qgx2vVCHv5gjMfOQaAqIMymqMBzLDeDpIjpjzwlJ2UdyoKuAFOM6V5UmXqMrbcP6migeF5Qnxyjug1MzuCzBgvAiyh9pg0v+Ce9Ugwnnw8ABJzcm8SlSo4Wor1z+yzIGkAuHI0o3uvAW/PLV1f9mDKwrqKWCkNhCfmFVl9dHtbfOxUGFVxwf9vozgkIuh9gWGVlyoKVkEOXiSLO/cgf14EEjvEbGo7OrUKJhQQe28KpcWnYUQ1eSFTyWh5hZTnFIFWGk08Mt5NxV9QBDCrSwiFghMFzTSreDf6ujw85JBkiaEfV9dvS4dbp9SnvxuW+swsecxd7ECqSOl/5uwWxrQnMhD7YtfMr51iXbX8c51wvvowzeZcHBfbUtQQa95JNaMqkTkop60SPTXKSRbCExGM4N5Q+qwvb3Q4yOG85q6wA4h5xF9zaxMzLkDbBlWOaBy/iSpyYNJ7FxFtspVjULjM+gC0YNAkS9KCrZ5R5dbZCaj6q3f3IrumF99qMym1hgQfZoWiriGLc9RjI1GmGaevfXxuqyPrPqlUEUuYVTyhZLpYOCNFNV30rDZzg8o1HC/8/Hmd4X49byBMMsgdJQG8=}
